### ISSUE TITLE
Issue: Cannot read property `createPublicClientApplication` of null

### ISSUE THREAD

**Issue by estruyf** [bittu/react-native-msal2#1]
Hi, I just found your library and wanted to give it a try in a new Expo app, but I stumbled upon the following issue:  `Cannot read property 'createPublicClientApplication' of null.`

I tested it with a simple React Native app, but as I found it was better to try it out with Expo, I used the sample app: https://docs.expo.dev/tutorial/create-your-first-app/ - but both give me the same issue.

## Things I did

- Created the app
- Installed the library `yarn add react-native-msal2`
- Added the following code in my app:

```js
import PublicClientApplication from "react-native-msal";

const config = {
  auth: {
    clientId: "<client-id>",
    authority:
      "https://login.microsoftonline.com/common",
    redirectUri: "msauth.com.example.app://auth",
  },
};
const scopes = ["openid", "profile", "email", "offline_access"];

const pca = new PublicClientApplication(config);

try {
  await pca.init();
} catch (error) {
  Alert.alert("Failed to initialize", error.message);
}
```

- Run the code on my phone and simulator, but both give the following alert:

![image](https://github.com/bittu/react-native-msal2/assets/2900833/2ecbe588-1bdb-4370-a37b-db8cc9b86a6c)

Do you have any idea what I'm doing wrong to get your library to work?

**Comment by bittu** [comment]
The code snippet you are using still shows you are refering to `react-native-msal` this plugin is referred as `react-native-msal2`. 
Please delete your `node_modules` and `package-lock.json` and make sure you only installed this package `npm install react-native-msal2` (or via yarn)
Also please run `npx pod-install` from root folder or `pod install ` from ios folder if you are running on ios devices.

**Comment by estruyf** [comment]
@bittu oops, I was testing out the library which you've forked, which gave the same issue.

I just removed all node modules, made sure only `react-native-msal2` was installed, and built it again. Same issue.

Are you using it in Expo as well?

**Comment by bittu** [comment]
Unfortunately no!! I have forked and modified this to use it in a non-expo project.
Could you please post the error that is logged into the console.

**Comment by estruyf** [comment]
This is the only error I get: `Cannot read property 'createPublicClientApplication' of null.`

**Comment by bittu** [comment]
Is this error also on Android?

**Comment by estruyf** [comment]
I'm only interested in iOS atm.

**Comment by bittu** [comment]
Are there any errors while installing pods. Do you see MSAL pod installed in `ios/Pods` .
Podfile.lock should have below entry
```
- MSAL (1.2.5):
  - MSAL/app-lib (= 1.2.5)
- MSAL/app-lib (1.2.5)
  ```

**Comment by estruyf** [comment]
Found a way to get it to work from Expo. I first had to create a build for iOS, once that is done and the pods are installed, I can work your library. The reason why I needed to do this, is because there is no Expo plugin reference present which maps the library. That is also why I got the error in the first place.

BTW, do you happen to know how to use Microsoft Authenticator for the login?

**Comment by bittu** [comment]
Glad it worked.
As i said my need was for a non-expo project. The original from which i forked was using `expo-module` which fails to build on windows. So i had to create this without expo-module.

For Microsoft Authenticator a 2FA needs to be enabled for your account. If it is for your personal then add your personal microsoft account to Authenticator.
